### ISSUE TITLE
Service crashes after setting a value

### ISSUE THREAD

**Issue by I-dont-need-name** [nbfc-linux/nbfc-linux#102]
Basically it just stops working when I set a value:
![image](https://github.com/nbfc-linux/nbfc-linux/assets/43914475/573352b3-4370-400b-b84b-a34530ae7568)
I don't know what the reason can be.
I'm on Manjaro linux, compiled the program myself from latest git. Idk what can be the reason. Running service with `--debug` flag doesn't show any information either.

**Comment by BachoSeven** [comment]
In order to be sure that you get the compilation flags correct for your system, I suggest uninstalling the manually compiled version, and using either an AUR helper or directly `makepkg -si` to compile one of the PKGBUILD that I provide on the AUR:

- https://aur.archlinux.org/packages/nbfc
- https://aur.archlinux.org/packages/nbfc-git

Please try and let me know if you still have issues.

**Comment by I-dont-need-name** [comment]
> In order to be sure that you get the compilation flags correct for your system, I suggest uninstalling the manually compiled version, and using either an AUR helper or directly `makepkg -si` to compile one of the PKGBUILD that I provide on the AUR:
> 
> * https://aur.archlinux.org/packages/nbfc
> * https://aur.archlinux.org/packages/nbfc-git
> 
> Please try and let me know if you still have issues.

Reinstalling (via `git clone` and `make install`) fixed the issue for me.

**Comment by BachoSeven** [comment]
Ok, great to hear. Still, I suggest you use the PKGBUILDs to be sure to get the compilation flags with the right locations for Arch, cheers.
