### ISSUE TITLE
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.7.3-200.fc39.x86_64

### ISSUE THREAD

**Issue by arthurbg951** [nbfc-linux/nbfc-linux#118]
When I change the fan speed velocity to 100 or -a i get this message:

Using 'Acer Nitro AN515-51' as model config
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.7.3-200.fc39.x86_64
Using 'ec_acpi' as EmbeddedControllerType
Using '/sys/class/hwmon/hwmon3/temp1_input' as temperature source
Using '/sys/class/hwmon/hwmon3/temp2_input' as temperature source
Using '/sys/class/hwmon/hwmon3/temp3_input' as temperature source
Using '/sys/class/hwmon/hwmon3/temp4_input' as temperature source
Using '/sys/class/hwmon/hwmon3/temp5_input' as temperature source

What should I do to stop this "error"?
Another question: I have noticed that only 1 fan start to work at 100% speed, is it a bug?

**Comment by braph** [comment]
The modprobe "error" occurs, because NBFC-Linux tries to find the kernel module that enables access to the embedded controller. It first tries ec_sys, then acpi_ec. I can fix this by suppressing the stderr while trying to load the modules.

For that other problem: Have you specified the right fan number for setting the speed? For example `nbfc set -f 0 -a` sets the first fan to automatic speed, `nbfc -f 1 -a` sets the second fan to automatic speed.

Regards,

Benjamin

**Comment by arthurbg951** [comment]
For the nbfc error would be nice if there is no message like an error. Maybe just a status to show which one ec_sys or acpi_ec is in usage.

Talking about the fans.. Would be nice if there is an option in the argument pharser to set both fans at same time. I've never thought that the problem with my fans is not in the nbfc or nvidia things, is that im not was specifying the -f argument. When I want to set a speed for the fan I aways use `nbfc set -s 100` then back to `nbfc set -a`. 

You helped me alot. Tanks. I would apreciate if you consider to implement this improovments. I am not a C programmer but this code works very well.

**Comment by braph** [comment]
Hello, I modified the project so `nbfc set` by default sets all available fans if `-f` is not given. Thanks for pointing out this improvement.
