### ISSUE TITLE
terrible documentation for a new user, and possibly a bug

### ISSUE THREAD

**Issue by iminsert** [nbfc-linux/nbfc-linux#28]
as someone who has light coding experience, but not familiar with with linux, this documentation is near useless.

 after following the "manual", there's an error that comes up as "this specified configuration file does not exist", after i the command "sudo nbfc config --set auto". ontop of needing to refer to 3 different sites to try even install the thing. documentation improvement greatly needed for the non-linux literate, and possible bug

**Comment by BachoSeven** [comment]
@iminsert trying to address your points separately:

- In the manual, the command `config` with the flag `--set` does not indicate `auto` as a possible argument; it says:
```
 -s, --set config
             Set a config
```
  meaning the argument should be the name of one of the provided configurations.

  If you wanted to get a recommendation for which configs might work on your laptop, you could use `nbfc config --recommend`; at any rate, the word `auto` only appears in the manual for the `set` subcommand, and in that context the command `nbfc set --auto` would tell `nbfc` to automatically manage fan speeds according to the current configuration (which is the default behaviour).

- Regarding the need to consult three sites in order to install this program, could you expand on it? It would be helpful to know how you got here and why it was difficult to find installation instructions. Keep in mind this is a rewrite of the original `nbfc` project, which was written in C# and abandoned for quite some time now.

**Comment by MikeSpeigle** [comment]
It seems to the spaces need to be removed and replaced with a underscore or something similar. For example I was having similar issues but as soon as I changed Asus ROG GL702vm.json to Asus_ROG_GL702VM.json the command sudo nbfc config --set Asus_ROG_GL702VM worked.

**Comment by BachoSeven** [comment]
@MikeSpeigle I mean as in all shell arguments which contain spaces I guess you would need to quote it, as in:
``` sh
sudo nbfc config --set "Asus ROG GL702vm"
```

**Comment by BachoSeven** [comment]
Closing this because of lack of response from OP
