### ISSUE TITLE
Setup on Ubuntu 20.04

### ISSUE THREAD

**Issue by AndreasKaratzas** [nbfc-linux/nbfc-linux#32]
Has anyone tried to setup `nbfc-linux` on an Ubuntu 20.04 distro? I tried and there are some wierd messages showing up.

```
❯ systemctl status nbfc_service.service
● nbfc_service.service - NoteBook FanControl service
     Loaded: loaded (/usr/local/lib/systemd/system/nbfc_service.service; enabled; vendor preset: enabled)
     Active: failed (Result: protocol) since Sat 2022-01-22 15:26:13 CST; 11s ago
    Process: 16836 ExecStartPre=/usr/local/bin/nbfc wait-for-hwmon (code=exited, status=0/SUCCESS)
    Process: 16837 ExecStart=/usr/local/bin/nbfc start (code=exited, status=0/SUCCESS)

Jan 22 15:26:13 omen systemd[1]: nbfc_service.service: Scheduled restart job, restart counter is at 5.
Jan 22 15:26:13 omen systemd[1]: Stopped NoteBook FanControl service.
Jan 22 15:26:13 omen systemd[1]: nbfc_service.service: Start request repeated too quickly.
Jan 22 15:26:13 omen systemd[1]: nbfc_service.service: Failed with result 'protocol'.
Jan 22 15:26:13 omen systemd[1]: Failed to start NoteBook FanControl service.
```

**Comment by BachoSeven** [comment]
I believe this is due to https://github.com/nbfc-linux/nbfc-linux/pull/27, where the default `confdir` and `prefix` where changed, to subdirectories of `/usr/local`. You can verify if this is indeed the cause of the error you're facing by inspecting the journal with

``` sh
journalctl -xeu nbfc_service.service
```

If that's the case, then it should be sufficient to change those parameters and re-build by running

``` sh
make clean && make && sudo make PREFIX=/usr confdir=/etc install
```

from the folder containing the git repo.

@braph, perhaps these are not the optimal defaults? The documentation in the README still points to `/etc/nbfc/nbfc.json` as the default configuration file location, so `confdir` should be set to `/etc` by default(?)

**Comment by rofl0r** [comment]
> so prefix should be set to / by default, I think.

if that's being done, it should be `/usr`, but with (sys)confdir being just `/etc`, so by default things will end up where 90% of distros use system-wide installed stuff.

> for users who just clone the repository on distros where nbfc-linux is not packaged this will cause confusion

unfortunately there's not really a real standard for makefile-only based build systems, and many developers that use/implemented such thing are brewing their own soup, however a set of best practices exist. for autoconf-based build systems the default for --prefix is always /usr/localal, so anyone experienced in its use would expect the behaviour. otoh `sysconfdir` is kind of an oddball, as it is in most distros just plain `/etc`, ignoring the `$prefix` used for the rest of things. anyway, i certainly agree that conf files ending up in /usr/local/etc by default is probably surprising for people not regularly building software from source.

**Comment by BachoSeven** [comment]
`confdir=/etc prefix=/usr` makes sense, that's actually what I ended up using in the package.

In the end I guess the main concern which requires any change is documentation, in order to clarify the configuration location for users not experienced in building from source or unaware of default paths.

**Comment by AndreasKaratzas** [comment]
Yeah, I think I got it now. Thanks :)
