### ISSUE TITLE
Willing to maintain nbfc-linux package for gentoo

### ISSUE THREAD

**Issue by x0rzavi** [nbfc-linux/nbfc-linux#51]
Hi, I've made an ebuild (synonymous to PKGBUILD on Arch) for nbfc-linux which works perfectly for me. But certainly, it needs more testing. It can be accessed from [here](https://github.com/x0rzavi/x0rzavi-overlay) under `sys-power/nbfc-linux`. The repo includes both a git and a stable release version (git for the reason if I ever fail to be quick enough to update and provided there are no breaking changes causing patching to fail)

Patches I've made/included:
1. Disable stripping binaries (To satisfy gentoo ebuild QA warning)
2. Selectively install completions on condition
3. OpenRC init.d service file added, needs checking that whether it does exactly what is intended

Suggestions/Questions:
1. Segregating completions installation under 3 different categories would be helpful
3. Should I make a PR to include OpenRC init script? Also then it would be needed to include a recipe to install that.

**Comment by x0rzavi** [comment]
Also looks like I'll need to add `acpi_ec` support, but I don't think those conditions will apply to gentoo users anyway

**Comment by BachoSeven** [comment]
@x0rzavi that's great! Unfortunately I don't use Gentoo so I cannot test this atm, but I can leave it open for any Gentoo users to give their feedback

Regarding 1. and 2., feel free to make a PR including the OpenRC file, and you can edit the `Makefile` to include its proper installation. However it should be an __optional__ recipe, as most users are on `systemd`. As for 1., feel free to separate the various shells' installation scripts in the same or another PR since it's such a small change.

**Comment by x0rzavi** [comment]
Later I thought that, separating completions would make installation complicated for regular users, it'll best to keep it in gentoo's package only. So, I made a PR only for openrc support.
