### ISSUE TITLE
Allow to run as non-root

### ISSUE THREAD

**Issue by I-dont-need-name** [nbfc-linux/nbfc-linux#56]
I know this program needs root privileges to run but there are other ways to make it work, for example doing `chmod u+s` on executable or smth. At the moment the piece of code in client.c checks for uid, making it possible to run the program only as a root user, even if another user has all the needed privileges. Please, consider changing this check a little bit to include such a use case, for me (and probably other people) it would improve scripting options.

**Comment by BachoSeven** [comment]
I believe the reason why you need privileges is also due to using the kernel module, the system-wide systemd service... In fact, the commands such as `nbfc status` which don't require privileges can be run indeed without root ones.

In order to achieve easier scripting, you may decide instead to use `/etc/sudoers` to allow for `nbfc` commands to be run without password:
```
%wheel ALL=(ALL:ALL) NOPASSWD: /usr/bin/nbfc
```

**Comment by braph** [comment]
Note, since version 0.2.0 you don't need root rights to change the fan speed via `nbfc set` anymore.
