### ISSUE TITLE
cant change embed controller type

### ISSUE THREAD

**Issue by zortos293** [nbfc-linux/nbfc-linux#78]
hello i cant change my embedded controller type but it doesent work
i tried using acpi_ec but it doesent apply
```
Using 'Acer Nitro AN515-51' as model config
Using 'ECSysLinux' as EmbeddedControllerType
Using '/sys/class/hwmon/hwmon4/temp1_input' as temperature source
Using '/sys/class/hwmon/hwmon4/temp2_input' as temperature source
Using '/sys/class/hwmon/hwmon4/temp3_input' as temperature source
Using '/sys/class/hwmon/hwmon4/temp4_input' as temperature source
Using '/sys/class/hwmon/hwmon4/temp5_input' as temperature source
Using '/sys/class/hwmon/hwmon4/temp6_input' as temperature source
Using '/sys/class/hwmon/hwmon4/temp7_input' as temperature source
```
Acer Nitro AN515-57
OS : Pop!_OS 22.04 LTS
CPU : 11th Gen Intel® Core™ i5-11400H
GPU : GeForce RTX 3060 Mobile

**Comment by Rizqirazkafi** [comment]
I've found a workaround for this, but it requires you to have a Windows install with Nitro Sense Software.

1. Boot into windows
2. Login
3. Fire up Nitro Sense
4. Make sure you can tweak your RGB Keyboard and fan speed
5. **RESTART** Windows, **NOT SHUTDOWN**.
6. Boot into Linux
7. nbfc-linux should be working

I think the problem here is that Linux can't read or access the register. It might also be that the fan/keyboard controller doesn't power up when we boot into Linux. So it'll only power up when we boot into Windows -> Login -> Run Nitro Sense.

**Comment by FoxeiZ** [comment]
You can also achieve the same result by using [this](https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module). I am currently using it with [this](https://github.com/x211321/RGB-Config-Acer-gkbbl-0) for the GUI.

I don't know why, but it seems like the fan doesn't recognize that you are changing value to it unless you change (?) something in the lighting of the keyboard; after that, it works just fine.

**Comment by kensad-ops** [comment]
try #65
